Repository mr-rishikesh/DevConnect, pull requests merged in 2025-08, with the labels that each got.

#29 Added Code of Conduct file
  CODE_OF_CONDUCT.md
Labels: documentation, GSSoC 25, Level 1

#41 Fix the navbar position
  client/src/components/Navbar.jsx
Labels: enhancement, GSSoC 25, Level 1, frontend

#43 Backend Refactor for Blog Structure & Post Management (#37)
  .gitignore
  server/.env.example
  server/controllers/auth.controller.js
  server/controllers/post.controller.js
  server/lib/cloudinary.js
  server/lib/upload.js
  server/lib/util.js
  server/middleware/auth.middleware.js
  server/model/post.model.js
  server/model/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/post.route.js
Labels: enhancement, GSSoC 25, Level 3

#53 feat: add dark/light mode toggle (Fixes #9)
  client/src/App.jsx
  client/src/components/HomeLanding.jsx
  client/src/components/Navbar.jsx
  client/src/components/ThemeToggle.jsx
  client/src/context/ThemeContext.jsx
  client/src/index.css
  client/src/store/useAuthStore.js
  client/tailwind.config.js
  package-lock.json
  package.json
  server/routes/authRoutes.js
Labels: GSSoC 25, Level 1
